// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ce38QKMtUTJC_XoFVbQfAZYaru4ZLZE',
    appId: '1:709297244159:ios:37b889f870667d859289ca',
    messagingSenderId: '709297244159',
    projectId: 'medicall-ae781',
    storageBucket: 'medicall-ae781.firebasestorage.app',
    androidClientId: '709297244159-gcnrp8d4it67qkfapvo7a6hs8sv6nd36.apps.googleusercontent.com',
    iosClientId: '709297244159-su2db1329ela7fc3k8mvqevcphfvc4q4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wtfFlutterProjects',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBhghKOXqxY0SAks3iD-acaksyGq5sLWk',
    appId: '1:709297244159:android:e489d526169f1a4d9289ca',
    messagingSenderId: '709297244159',
    projectId: 'medicall-ae781',
    storageBucket: 'medicall-ae781.firebasestorage.app',
  );

}